# This file was automatically generated by the CUTLASS 3.5.0 Python interface (https://github.com/nvidia/cutlass/python)

from setuptools import setup
from torch.utils.cpp_extension import BuildExtension, CUDAExtension

setup(
    name='linearGelu',
    ext_modules=[
        CUDAExtension('linearGelu', [
            'linearGelu.cpp',
            'linearGelu_kernel.cu',
        ],
        include_dirs=['/dfs6/pub/sheikhh1/envs/sciml/lib/python3.10/site-packages/cutlass_library/source/include', '/dfs6/pub/sheikhh1/envs/sciml/lib/python3.10/site-packages/cutlass_library/source/tools/util/include'],
        extra_compile_args={
            'cxx': ['-std=c++17'],
            'nvcc': ['-std=c++17', ],
        },
        libraries=['cuda']
        ),
    ],
    cmdclass={
        'build_ext': BuildExtension
    })

